[package]
name = "wiregc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gdk-pixbuf = "0.18.3"
glib = "0.18.4"
gtk = "0.18.1"
